### ISSUE TITLE
Poor performance on Android

### ISSUE THREAD

**Issue by ipanamski** [VirtuoWorks/CanvasCameraPlugin#37]
The performance is poor running on a modern android smartphone.
When I set the resolution to 1280x720, the fps drops below 30 (lags).
If I set `use: 'data'` it's even worse.
Is there any way to speed things up or is it a canvas limitation?

**Comment by Sami-Radi** [comment]
Hello,

Indeed performance is poor on Android and iOS with a high CPU load. The only way to speed things up is to set a smaller resolution. 

Currently the plugin works by running a camera preview, and for each recorded frame from the phone, the plugin converts/resizes/rotates the frame and then tries to draw the frame in the canvas. If a previous frame is currently being drawn, the current frame is discarded.

The only way to improve performance would be to change completely the way the plugin works. Rather than trying to render each frame, the webview script should request the native part for a frame from a raw camera preview, process it, draw it and then request a new frame. We are currently working on a new version of the plugin which should work this way but we are far from having anything to release.

Best Regards,
